# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af83c5af95c861cb5d88ef1411898bfcc0f1a026257e61466e011ba43ecf31fdb3abdcac2b3d2688b09cec17441332f94cd53ac9d493f087205cd02d2534cace

test:
  secret_key_base: 23ff98864daf142b8a31eec232c04682292fb0b81cdd65a2f4adc0cc51f32e0a5439855c9cc0a159346807223db455ff566f325affa73869a12b1edb2aa09431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
